/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2022-01-06 12:26:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<footer class=\"section-text-white footer footer-links bg-darken\">\n");
      out.write("<div class=\"footer-body container\">\n");
      out.write("    <div class=\"row\">\n");
      out.write("        <div class=\"col-sm-6 col-lg-3\">\n");
      out.write("            <a class=\"footer-logo\" href=\"./\">\n");
      out.write("                <span class=\"logo-element\">\n");
      out.write("                    <span class=\"logo-tape\">\n");
      out.write("                        <span class=\"svg-content svg-fill-theme\" data-svg=\"./images/svg/logo-part.svg\"></span>\n");
      out.write("                    </span>\n");
      out.write("                    <span class=\"logo-text text-uppercase\">\n");
      out.write("                        <span>L</span>ittle Cinema</span>\n");
      out.write("                </span>\n");
      out.write("            </a>\n");
      out.write("            <br>\n");
      out.write("            <div class=\"footer-content\">\n");
      out.write("                <p class=\"footer-text\">서울특별시 강남구 테헤란로 124 4층\n");
      out.write("                    <br/>(역삼동, 삼원타워)</p>\n");
      out.write("                <p class=\"footer-text\">Call us:&nbsp;&nbsp;02-6255-8002</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-sm-6 col-lg-3\">\n");
      out.write("            <h5 class=\"footer-title text-uppercase\">영화관</h5>\n");
      out.write("            <ul class=\"list-unstyled list-wide footer-content\">\n");
      out.write("                <li>\n");
      out.write("                    <a class=\"content-link\" href=\"seattable\">좌석배치도</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a class=\"content-link\" href=\"faq\">고객센터</a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-sm-6 col-lg-3\">\n");
      out.write("            <h5 class=\"footer-title text-uppercase\">영화정보</h5>\n");
      out.write("            <ul class=\"list-unstyled list-wide footer-content\">\n");
      out.write("                <li>\n");
      out.write("                    <a class=\"content-link\" href=\"timetable\">상영시간표</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a class=\"content-link\" href=\"playing\">현재 상영작</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a class=\"content-link\" href=\"scheduled-movies\">상영 예정작</a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-sm-6 col-lg-3\">\n");
      out.write("            <h5 class=\"footer-title text-uppercase\">Follow</h5>\n");
      out.write("            <ul class=\"list-wide footer-content list-inline\">\n");
      out.write("                <li class=\"list-inline-item\">\n");
      out.write("                    <a class=\"content-link\" href=\"#\"><i class=\"fab fa-slack-hash\"></i></a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"list-inline-item\">\n");
      out.write("                    <a class=\"content-link\" href=\"#\"><i class=\"fab fa-twitter\"></i></a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"list-inline-item\">\n");
      out.write("                    <a class=\"content-link\" href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"list-inline-item\">\n");
      out.write("                    <a class=\"content-link\" href=\"#\"><i class=\"fab fa-dribbble\"></i></a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"list-inline-item\">\n");
      out.write("                    <a class=\"content-link\" href=\"#\"><i class=\"fab fa-google-plus-g\"></i></a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"list-inline-item\">\n");
      out.write("                    <a class=\"content-link\" href=\"#\"><i class=\"fab fa-instagram\"></i></a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("            <!-- \n");
      out.write("            <h5 class=\"footer-title text-uppercase\">Subscribe</h5>\n");
      out.write("            <div class=\"footer-content\">\n");
      out.write("                <p class=\"footer-text\">Get latest movie news right away with our subscription</p>\n");
      out.write("                <form class=\"footer-form\" autocomplete=\"off\">\n");
      out.write("                    <div class=\"input-group\">\n");
      out.write("                        <input class=\"form-control\" name=\"email\" type=\"email\" placeholder=\"Your email\" />\n");
      out.write("                        <div class=\"input-group-append\">\n");
      out.write("                            <button class=\"btn btn-theme\" type=\"submit\"><i class=\"fas fa-angle-right\"></i></button>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("             -->\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<div class=\"footer-copy\">\n");
      out.write("    <div class=\"container\">Copyright 2019 &copy; AmigosThemes. All rights reserved.</div>\n");
      out.write("</div>\n");
      out.write("</footer>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
